### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by lecoqjacob** [BirdeeHub/nixCats-nvim#2]
I just wanted to extend my gratitude for this setup, it inspired me to move my neovim implementation into nix and it is a very wonderful setup (https://github.com/lecoqjacob/andromeda-neovim)! I really wanted to figure a way to use lazy.nvim for plugin management and I think i found a nice system to pull from local nix plugins and only fetch git plugins if needed. Anyway thanks :) I was struggling for a while on the best setup

**Comment by BirdeeHub** [comment]
Oh wow! I'm going to have to check this out! Thanks for telling me about neoconf btw. I added it cause it was in the fork you made. You really made it your own though and that makes me happy.

**Comment by BirdeeHub** [comment]
Also I added your repo to the readme :)

**Comment by BirdeeHub** [comment]
Probably shoulda asked if that was ok with you first idk but, it seemed like a thing to do.
