### ISSUE TITLE
Override package settings / categories in home-manager or darwin module

### ISSUE THREAD

**Issue by chrishrb** [BirdeeHub/nixCats-nvim#20]
If i import the flake as a homeModule or darwinModule I would like to override just a few settings / categories but not redefine the whole definition. So instead of redefining everything:

```nix
home-manager.users.${config.user} = {
  imports = [ inputs.chris-nvim.homeModule ];
  
  chrisNvim = {
    enable = true;
  
    packages = {
      chrisNvim = { pkgs, ... }: {
        settings = {
          # will check for config in the store rather than .config
          wrapRc = true;
          configDirName = "chrishrb-nvim";
          aliases = [ "vi" "vim" ];
          # caution: this option must be the same for all packages.
          # nvimSRC = inputs.neovim;
        };
        categories = {
          lazy = true;
          generalBuildInputs = true;
          general = true;
  
          # languages
          go = true;
          python = true;
          web = true;
          java = true;
          devops = true;
          latex = false;
  
          # you could also pass something else:
          colorscheme = "catppuccin";
        };
      };
    };

};
```

, i would like to override only a few values e.g.

```nix
home-manager.users.${config.user} = {
  imports = [ inputs.chris-nvim.homeModule ];
  
  chrisNvim = {
    enable = true;
  
    packages = {
      chrisNvim = { pkgs, ... }: {
        categories = {
          python = true;
          web = true;
        };
      };
    };

};
```

Is this possible right now?

**Comment by BirdeeHub** [comment]
Yes, kinda.

The flake outputs its packageDefinitions function separately as well, so when using the flake or nixExpressionsFlakeOutputs templates you can just take the value and override specific ones?

Theres a utils.mergeCatDefs that can be used to merge function outputs together? Im sorry its not named better but its literally just is a function that takes 2 functions and an argument, and calls both of them with the argument and updates the output of the second from the output of the first.

However in classic nix fashion, its poorly documented rn

from :help nixCats.flake.outputs.exports
```
<mergeCatDefs> oldCats: newCats:
for merging category definitions,
will recursively update up to the first thing not an attrset.
For our purposes, we do not consider derivations to be attrsets.
```

You could do something like this

```nix
home-manager.users.${config.user} = {
  imports = [ inputs.chris-nvim.homeModule ];
  inherit (inputs.chris-nvim) utils packageDefinitions;
  
  chrisNvim = {
    enable = true;
    packageNames = [ "chrisNvim" ];
  
    packages = {
      chrisNvim = (utils.mergeCatDefs packageDefinitions.chrisNvim ({ pkgs, ... }: {
        categories = {
          python = true;
          web = true;
        };
      }));
    };

};
```

This is great for things like, if you wanted to make a dev shell with only 1 or 2 things from your normal config for example.

However, if Im not using it in a dev shell specific setting, I usually find it easier to just make a new package in my flake.
I have mine kinda factored into a base that I override like this:

https://github.com/BirdeeHub/birdeeSystems/blob/314a7e1622ef165435f950bb987d24e9af81717b/common/birdeevim/default.nix#L313-L414

And then I install it via my module

https://github.com/BirdeeHub/birdeeSystems/blob/314a7e1622ef165435f950bb987d24e9af81717b/homes/birdee.nix#L22C1-L25C5

**Comment by chrishrb** [comment]
big thanks for the fast and detailed reply! thats what I was looking for - it works 👍
