### ISSUE TITLE
Lua issue while migrating to templates

### ISSUE THREAD

**Issue by Doosty** [BirdeeHub/nixCats-nvim#23]
Hi, when i cloned this repo the lua was working, however when i try to migrate the lua into flake or module templates i am getting errors that modules cannot be found. I am not that good with lua or nix so this is just my skill issue. Help appreciated.

```nix
    # flake.nix
    luaPath = "${./lua/myLuaConf}";
```

```
-- lua/myLuaConf/init.lua
-- i tried removing myLuaConf. from the lua files but then a slightly different error tell me that plugins cannot be loaded
require("myLuaConf.plugins")
require("myLuaConf.LSPs")
require('myLuaConf.format')
if nixCats('debug') then
  require('myLuaConf.debug')
end
```

```
tree -L 3
.
├── lua
│  └── myLuaConf
│     ├── debug
│     ├── format
│     ├── LSPs
│     ├── plugins
│     └── init.lua
├── overlays
│  └── default.nix
├── flake.lock
└── flake.nix
```
lua error on startup
```
Error detected while processing /nix/store/1nnvi6r112qxrcvyhws7ijrnwr6agjri-init.lua:
E5113: Error while calling lua chunk: /nix/store/1nnvi6r112qxrcvyhws7ijrnwr6agjri-init.lua:2: /nix/store/1nnvi6r112qx
rcvyhws7ijrnwr6agjri-init.lua../nix/store/3256jm73f52aakaslqpj7d84yh9677is-init.vim[13]../nix/store/6n49qncsxfkxshi5q
6yw9hfna0avjw0w-nixCats-special-rtp-entry-LuaConfig/init.lua: Vim(source):E5113: Error while calling lua chunk: ...hf
na0avjw0w-nixCats-special-rtp-entry-LuaConfig/init.lua:1: module 'myLuaConf.plugins' not found:
        no field package.preload['myLuaConf.plugins']
        no file '/nix/store/k85k151qrrl98gfbj5z00h36a5kj4fwy-luajit-2.1.1693350652-env/share/lua/5.1/myLuaConf/plugin
s.lua'
        no file '/nix/store/k85k151qrrl98gfbj5z00h36a5kj4fwy-luajit-2.1.1693350652-env/share/lua/5.1/myLuaConf/plugin
s/init.lua'
        no file '/nix/store/k85k151qrrl98gfbj5z00h36a5kj4fwy-luajit-2.1.1693350652-env/lib/lua/5.1/myLuaConf/plugins.
so'
        no file '/nix/store/k85k151qrrl98gfbj5z00h36a5kj4fwy-luajit-2.1.1693350652-env/lib/lua/5.1/myLuaConf.so'
stack traceback:
        [C]: in function 'require'
        ...hfna0avjw0w-nixCats-special-rtp-entry-LuaConfig/init.lua:1: in main chunk
        [C]: in function 'source'
        /nix/store/1nnvi6r112qxrcvyhws7ijrnwr6agjri-init.lua:2: in main chunk
stack traceback:
        [C]: in function 'source'
        /nix/store/1nnvi6r112qxrcvyhws7ijrnwr6agjri-init.lua:2: in main chunk
Press ENTER or type command to continue
```

https://github.com/Doosty/nixCats-nvim-flake

**Comment by BirdeeHub** [comment]
An easier way to think of it is this. Whatever path you put in luaPath, is going to be copied to the store, and nvim is gonna look there instead of ~/.config/nvim

**Comment by blazp7** [comment]
I actually had to copy over `init.lua` from the toplevel directory in your repo for everything to function correctly. I first added init.lua with only `require('myLuaConf')` and that fired up the app without a startup error however all the keybinds were broke and that gave me a clue that much more of lua is missing and so i found the needed file in the repo.

I also just want to say thanks alot for your work, i love that i can manage my configs with nix and use `nix run` anywhere to get to my editor.

**Comment by BirdeeHub** [comment]
To see what info is being passed, there are several user commands starting with NixCats

They are outlined in :h nixCats at the bottom.

One of those pieces of info will be the path to your config directory in the store. You can take a look at it there if you like to understand what is going on better.

**Comment by Doosty** [comment]
Sorry posted with wrong account before.

**Comment by BirdeeHub** [comment]
Also, I just realized, you have no init.lua

Its a normal config folder it needs an init.lua at the root of it.

Like, at the same level as your flake.nix

**Comment by BirdeeHub** [comment]
And thanks for the words of encouragement :)

I knew what I wanted so I made it :)

The nixExpressionFlakeOutputs template is my personal one stripped down in a template, Its literally the outputs function from flake.nix, but in a default.nix that you call like a function and recieve the normal flake outputs.

I then export the packages from the top level of my system flake so that I can nix run them from anywhere, and also have it be inside my system flake :)

My [personal config](https://github.com/BirdeeHub/birdeeSystems/blob/main/common/birdeevim) has gotten a little complicated lol but its still just the nixExpressionFlakeOutputs template
