### ISSUE TITLE
Treesitter parsers not available to the kickstart-nvim template

### ISSUE THREAD

**Issue by NeilDarach** [BirdeeHub/nixCats-nvim#41]
Starting an nvim instance from the kickstart template loads treesitter parsers from the nvim distribution, not the nixCats plugins store entry.

clone repository and 'cd' into it
nix run ./nix/templates/kickstart-nvim#

:checkhealth treesitter shows only 7 parsers, all loaded from /nix/store/&lt;hash>-neovim-unwrapped-0.10.1/lib/nvim/parser

nix run .#
:checkhealth treesitter shows many parsers, loaded from /nix/store/&lt;hash>-vim-pack-dir/pack/myNeovimPackages/start/vimplugin-treesitter-grammer-ALL-INCLUDED/parser

**Comment by BirdeeHub** [comment]
awww shoot let me check rq. I updated the template recently......

**Comment by BirdeeHub** [comment]
yeah... youre right....

**Comment by BirdeeHub** [comment]
ok well, new templates are bad I guess.........

**Comment by BirdeeHub** [comment]
I will revert the luaUtils template I suppose to its previous version, or something similar to it

**Comment by BirdeeHub** [comment]
I thought I built it and checked..........

**Comment by BirdeeHub** [comment]
Honestly wish I never added a lazy.nvim wrapper XD

**Comment by BirdeeHub** [comment]
It doesnt help that nixpkgs is currently messing up with treesitter grammars....

https://github.com/NixOS/nixpkgs/issues/332580#issuecomment-2308526316

**Comment by BirdeeHub** [comment]
Basically, if treesitter grammars werent in flux rn, I would not have changed this template to begin with, so I want to find some other fix for it....

**Comment by BirdeeHub** [comment]
Give me a few hours I wanna find a way to fix this that doesnt involve going back to exactly how it was before

**Comment by NeilDarach** [comment]
No urgency from my position.  I'm still just figuring out which bits I can get to work.
To be honest it's nice that I hadn't done something stupid with my attempts at config.
I'm going to be checking out the main flake implementation anyway to see how that might work for me.

**Comment by BirdeeHub** [comment]
honestly, using lze or lz.n it feels a lot like using lazy.nvim

If you want a really complex example, heres my useage of the flake implementation plus lze

https://github.com/BirdeeHub/birdeeSystems/tree/main/common/birdeevim

I highly encourage not using lazy.nvim


But in the meantime, It will work if you replace lua/nixCatsUtils/lazyCat.lua with this in the next comment

**Comment by BirdeeHub** [comment]
```lua
local M = {}

function M.mergePluginTables(table1, table2)
  return vim.tbl_extend('keep', table1, table2)
end

---used to help provide the list of plugin names for lazy wrapper.
---@param pluginTable table|string[]|nil
---@return string[]
function M.getTableNamesOrListValues(pluginTable)
  if pluginTable == nil then
    return {}
  end
  for key, _ in pairs(pluginTable) do
    if type(key) ~= 'string' then
      return vim.tbl_values(pluginTable)
    end
    break
  end
  return vim.tbl_keys(pluginTable)
end

---lazy.nvim wrapper
---@param pluginTable table|string[]|nil
---@param nixLazyPath string|nil
---@param lazySpecs any
---@param lazyCFG table
function M.setup(pluginTable, nixLazyPath, lazySpecs, lazyCFG)

  local function regularLazyDownload()
    local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
    if not vim.loop.fs_stat(lazypath) then
      vim.fn.system {
        'git',
        'clone',
        '--filter=blob:none',
        'https://github.com/folke/lazy.nvim.git',
        '--branch=stable', -- latest stable release
        lazypath,
      }
    end
    return lazypath
  end

  local ok, nixCats = pcall(require,'nixCats')
  local lazypath
  if not ok then
    -- No nixCats? Not nix. Do it normally
    lazypath = regularLazyDownload()
    vim.opt.rtp:append(lazypath)
  else
    -- Else, its nix, so we wrap lazy with a few extra config options
    lazypath = nixLazyPath
    -- and also we probably dont have to download lazy either
    if lazypath == nil then
      lazypath = regularLazyDownload()
    end

    local oldPath
    local lazypatterns
    if type(lazyCFG) == "table" and type(lazyCFG.dev) == "table" then
      if type(lazyCFG.dev.patterns) ~= 'table' then
        lazypatterns = M.getTableNamesOrListValues(pluginTable)
      else
        local toInclude = lazyCFG.dev.patterns
        vim.list_extend(toInclude, M.getTableNamesOrListValues(pluginTable))
        lazypatterns = toInclude
      end
      oldPath = lazyCFG.dev.path
    end

    local myNeovimPackages = nixCats.vimPackDir .. "/pack/myNeovimPackages"

    local newLazyOpts = {
      performance = {
        rtp = {
          reset = false,
        },
      },
      dev = {
        path = function(plugin)
          local path = nil
          if type(oldPath) == "string" and vim.fn.isdirectory(oldPath .. "/" .. plugin.name) == 1 then
            path = oldPath .. "/" .. plugin.name
          elseif type(oldPath) == "function" then
            path = oldPath(plugin)
            if type(path) ~= "string" then
              path = nil
            end
          end
          if path == nil then
            if vim.fn.isdirectory(myNeovimPackages .. "/start/" .. plugin.name) == 1 then
              path = myNeovimPackages .. "/start/" .. plugin.name
            elseif vim.fn.isdirectory(myNeovimPackages .. "/opt/" .. plugin.name) == 1 then
              path = myNeovimPackages .. "/opt/" .. plugin.name
            else
              path = "~/projects/" .. plugin.name
            end
          end
          return path
        end,
        patterns = lazypatterns or M.getTableNamesOrListValues(pluginTable),
      }
    }
    lazyCFG = vim.tbl_deep_extend("force", lazyCFG or {}, newLazyOpts)
    -- do the reset we disabled without removing important stuff
    vim.opt.rtp = {
      require('nixCats').configDir,
      require('nixCats').nixCatsPath,
      require('nixCats').pawsible.allPlugins.ts_grammar_plugin,
      vim.fn.stdpath("data") .. "/site",
      lazypath,
      vim.env.VIMRUNTIME,
      vim.fn.fnamemodify(vim.v.progpath, ":p:h:h") .. "/lib/nvim",
      require('nixCats').configDir .. "/after",
    }
  end

  require('lazy').setup(lazySpecs, lazyCFG)
end

return M
```

**Comment by BirdeeHub** [comment]
require('nixCats').pawsible.allPlugins.ts_grammar_plugin,

I have a gripe with this variable....

I want to name it ts_grammar_path

But I also dont want to annoy ppl....

**Comment by BirdeeHub** [comment]
It may have to stay that way.....

**Comment by BirdeeHub** [comment]
basically, last night I removed 

```lua
    -- do the reset we disabled without removing important stuff
    vim.opt.rtp = {
      require('nixCats').configDir,
      require('nixCats').nixCatsPath,
      require('nixCats').pawsible.allPlugins.ts_grammar_plugin,
      vim.fn.stdpath("data") .. "/site",
      lazypath,
      vim.env.VIMRUNTIME,
      vim.fn.fnamemodify(vim.v.progpath, ":p:h:h") .. "/lib/nvim",
      require('nixCats').configDir .. "/after",
    }
 ```
 
 Because I thought, while this would make it faster, it was in the correct order before, so reset = false should be enough and then I can deal with whatever nixpkgs does with treesitter grammars better

**Comment by NeilDarach** [comment]
Thanks for the amazingly fast response. I’ll give it a go tomorrow.

**Comment by BirdeeHub** [comment]
mhmm :) you also caught me at a good time to be fair XD

**Comment by BirdeeHub** [comment]
Fixed XD

**Comment by BirdeeHub** [comment]
but yeah basically I was trying to deal with

https://github.com/NixOS/nixpkgs/issues/332580#issuecomment-2308526316

by doing less, and the stuff I did less of was needeed.

**Comment by BirdeeHub** [comment]
@NeilDarach if anything else is broken, do let me know but to my knowledge, thats it.

**Comment by BirdeeHub** [comment]
I also took the opportunity to add some future proofing to the internals to make my life easier when they fix how theyre doing treesitter grammars XD
