### ISSUE TITLE
Lazy-template nix build

### ISSUE THREAD

**Issue by phortonssf** [BirdeeHub/nixCats-nvim#43]
Thank you for all the work you put in on this project. What is your recommended way to use the result of **nix build .** when using the [lazy-template](https://github.com/BirdeeHub/nixCats-nvim/tree/main/nix/templates/kickstart-nvim). Thank you.

**Comment by BirdeeHub** [comment]
It is its own flake

You would import it in your config and install the packages you output :)

You could then even [modify them further there](https://nixcats.org/nixCats_overriding.html) although I think thats not what you are asking about yet.

Alternatively, you could move the overlays, categoryDefinitions and packageDefinitions over to [this template](https://github.com/BirdeeHub/nixCats-nvim/blob/main/nix/templates/nixExpressionFlakeOutputs/default.nix) and then move the flake inputs to your system flake inputs, and call it like a function with your system flake inputs to recieve all the normal flake outputs if you want the directory INSIDE your system config.

---

quick note about the kickstart-nvim template

The kickstart-nvim template is meant to be an example of how to use the lazy.nvim wrapper in your existing config that uses lazy.nvim. You search for the `NOTE: nixCats:` string and look at the way it works, and replace your lazy.setup call with a call to the wrapper as specified, and pass it the list of nix-installed plugins from the nixCats plugin.

If you are starting out using that, that is cool, kickstart.nvim is a good place to start learning neovim, and this is not much different, just know that the wrapper will tell lazy.nvim not to download things downloaded by nix as long as the name is matching the url. If it doesnt, you might have to pass it an extra item in the list as shown in that template, but if you do not, lazy.nvim will still attempt to download it itself, which will likely still work.

**Comment by BirdeeHub** [comment]
Also, if you have any more questions, I would love to answer them, but please post any future questions in discussions so that the answers may remain archived for others to benefit from :) Issues is for bugs, dissusions is for help :)

**Comment by BirdeeHub** [comment]
I just realized, you asked *specifically* about `nix build .`

`nix build .` just builds the result to a ./result directory

so you would run ./result/bin/packagename

But for installing it into your nix config, see above.

I figured you were asking about installing it to your nix config because nix build does the same thing as with any other package.
