### ISSUE TITLE
NixCatsPath for non nix deployment

### ISSUE THREAD

**Issue by mattbrandman** [BirdeeHub/nixCats-nvim#46]
In the kickstart nvim template if you are not in nix it appears to error out as nixcatspath is nil and cannot be appended to. I worked around it by pulling the library into a an if statement around nixcats existing but maybe I'm missing something!

**Comment by BirdeeHub** [comment]
I made some edits to the template without building on a VM without nix a while back.

It looks like I forgot to check require('nixCatsUtils').isNixCats on [this line](https://github.com/BirdeeHub/nixCats-nvim/blob/bec49a10a76ceeaa93dfaa29d49104822232caf9/nix/templates/kickstart-nvim/init.lua#L521)

Not all values from the nixCats plugin are available when not on nix because there is no nix to create the plugin there.

**Comment by BirdeeHub** [comment]
the version I just committed should work, I dont see any other ones I forgot anywhere.

I havent fixed any similar issues in the example config yet if there are any.

Will be testing on a vm whenever the ubuntu vm finishes installing XD

**Comment by BirdeeHub** [comment]
Yup! That was it

**Comment by BirdeeHub** [comment]
Ok now to mess with the example config and make sure that one still works too I guess

**Comment by BirdeeHub** [comment]
I also cant guarantee mason will successfully download lsps when no nix is involved.

That is entirely dependent on whether you have the dependencies to run said lsp installed on your machine.

**Comment by BirdeeHub** [comment]
Basically, no, you didnt miss anything, I did.

**Comment by BirdeeHub** [comment]
Ill leave this open until I get around to fixing the downloading of lazydev when no nix was involved in the main example config.

**Comment by BirdeeHub** [comment]
Yeah it has an enable option you need ot use

And then you also have to pass it a list of names of which package outputs to build, which are the names from packageDefinitions

You have all the capabilities of using override on the config you import via the module options, but you can also just enable them and use the ones as you had them in the template as youre doing

You can also jsut add the packages from the flake directly to your packages list too

**Comment by BirdeeHub** [comment]
When I get around to it, I'm just gonna swap catPacker luaUtils file to use paq.nvim probably. pckr apparently does some shenanigans with the packpath that makes it a little more annoying.

I'm also planning on adding more lazy loading to the example config, unsure if I want to wait and do both at once, or just swap pckr for paq now and then do that later.

**Comment by BirdeeHub** [comment]
https://github.com/BirdeeHub/nixCats-nvim/commit/43c7fbb94e3fdbb6fecc090746e9455c1e05ec58

As of this commit, this is now resolved, at least until I forget something again in one of the example configs when I make the base example one do more lazy loading
