### ISSUE TITLE
kickstart-nix example fails to load configs

### ISSUE THREAD

**Issue by Clarkery** [BirdeeHub/nixCats-nvim#59]
I'm attempting to run `nix shell github:BirdeeHub/nixCats-nvim?dir=templates/kickstart-nvim ` under NixOS-WSL.
Not sure if the WSL part is relevent or it is a general issue, but it fails when trying to run nvim with the following lua error.

```Error detected while processing /nix/store/3ccc03i3gwsds9indfr04xyp68q1ym27-init.lua:
E5113: Error while calling lua chunk: ...special-rtp-entry-LuaConfig/lua/nixCatsUtils/lazyCat.lua:73: attempt to concatenate field 'vimPackDir' (a nil value)
stack traceback:
        ...special-rtp-entry-LuaConfig/lua/nixCatsUtils/lazyCat.lua:73: in function 'setup'
        ...az9xw1cgpah-nixCats-special-rtp-entry-LuaConfig/init.lua:290: in main chunk
        [C]: in function 'dofile'
        /nix/store/3ccc03i3gwsds9indfr04xyp68q1ym27-init.lua:17: in main chunk
Press ENTER or type command to continue  ```

**Comment by BirdeeHub** [comment]
nope its a new regression that I accidentally added while adding the test library. Working on it, should just take a moment

**Comment by BirdeeHub** [comment]
Fixed!

**Comment by BirdeeHub** [comment]
Needs a test too but its fixed at least XD

**Comment by BirdeeHub** [comment]
Thank you so much for making me aware of this by the way.

**Comment by BirdeeHub** [comment]
Ok, has tests now so hopefully I dont do that again haha

Basically, I was requiring nixCats in the wrapper before the global value was defined that it was getting the value from, so the field in the plugin was turning up nil

**Comment by BirdeeHub** [comment]
I found another issue I added last week as well.

I had good intentions but I did not do enough checking last week.

My deprecation warning I added for an old lua variable breaks the debug info command because metatables are meh...

So, all thats fixed now so thats good.

**Comment by BirdeeHub** [comment]
Ok, so I went through and fixed all the regressions from last week

How all those snuck in there I do not know. But Its fixed now.

**Comment by BirdeeHub** [comment]
ok thats all of this last weeks carnage fixed for sure :)

Now to work on my goals for the help and tests...
